server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: xxxxx-your-client-id-xxxxx
            client-secret: xxxxx-your-client-secret-xxxxx
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, https://graph.microsoft.com/user.read
            client-name: Azure
        provider:
          azure:
            authorization-uri: https://login.microsoftonline.com/common/oauth2/authorize
            token-uri: https://login.microsoftonline.com/common/oauth2/token
            user-info-uri: https://login.microsoftonline.com/common/openid/userinfo
            jwk-set-uri: https://login.microsoftonline.com/common/discovery/keys

azure:
  activedirectory:
    graphapiurl: https://graph.windows.net/
    aadsiginurl: https://login.microsoftonline.com/
    aadmemberurl: https://graph.windows.net/me/memberOf
    tenantid: xxxxx-your-tenant-id-xxxxx
